### PR TITLE
fix: add quotes to identifier with special character 

### LINKED ISSUE #182: [Bug] Import tool generates error data format.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

main.yaml

```yaml
name: Backport merged pull request
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      - name: Create backport pull requests
        uses: korthout/backport-action@v1
```

Run with the import tool

### 2. What did you expect to see? (Required)

The right KCL code

```python
"""
This file was generated by the KCL auto-gen tool. DO NOT EDIT.
Editing this file might prove futile when you re-run the KCL auto-gen generate command.
"""

name = "Backport merged pull request"
on = {
    pull_request_target = {
        types = [
            "closed"
        ]
    }
}
permissions = {
    contents = "write"
    "pull-requests" = "write"
}
jobs = {
    backport = {
        name = "Backport pull request"
        "runs-on" = "ubuntu-latest"
        $if = "github.event.pull_request.merged"
        steps = [
            {
                uses = "actions/checkout@v3"
            }
            {
                name = "Create backport pull requests"
                uses = "korthout/backport-action@v1"
            }
        ]
    }
}

```

### 3. What did you see instead (Required)

The wrong KCL code

```python
"""
This file was generated by the KCL auto-gen tool. DO NOT EDIT.
Editing this file might prove futile when you re-run the KCL auto-gen generate command.
"""

name = "Backport merged pull request"
on = {
    pull_request_target = {
        types = [
            "closed"
        ]
    }
}
permissions = {
    contents = "write"
    pull-requests = "write" # Lost ""
}
jobs = {
    backport = {
        name = "Backport pull request"
        runs-on = "ubuntu-latest"
        $if = "github.event.pull_request.merged"
        steps = [
            {
                uses = "actions/checkout@v3"
            }
            {
                name = "Create backport pull requests"
                uses = "korthout/backport-action@v1"
            }
        ]
    }
}

```

### 4. What is your KCL components version? (Required)

v0.7.0-alpha.2

### PR DESCRIPTION
**Pull request by jakezhu9**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references:

- [ ] N
- [x] Y 

fix #182 

#### 2. What is the scope of this PR (e.g. component or file name):

pkg/tools/gen

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: pkg/tools/gen/template.go [hunk 1]
```diff
@@ -128,6 +128,9 @@ func formatName(name string) string {
 	if _, ok := kclKeywords[name]; ok {
 		return fmt.Sprintf("$%s", name)
 	}
+	if strings.Contains(name, "-") {
```
Comment (Peefy) [inline pkg/tools/gen/template.go]: Perhaps a regular expression should be used here to determine whether it is a valid identifier expression rather than a simple string check, as it may also be in the form of `a.b`. cc @jakezhu9

**Review by Peefy — APPROVED** [review]
Good Job! LGTM
