### PR TITLE
Dev/xiarui.xr/update parse deps

### LINKED ISSUE #17: ListDownStreamFiles does not support deleted files in changed files list
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use the test data in ```pkg/tools/list/testdata/complicate/appops/projectD``` as an example: 

set the ListDepsOption.ChangedPaths and contains a deleted file path in it, then call ListDownStreamFiles API, for example: 
  ```
  depParser, err := NewImportDepParser("pkg/tools/list/testdata/complicate/", DepOption{Files: []string{"appops/projectD/base/base.k", "appops/projectD/dev/main.k"}, ChangedPaths: []string{"base/frontend/not_exist.k"}})
  affected := depParser.ListDownStreamFiles()
  ```

### 2. What did you expect to see? (Required)

down stream files should be:
[]string{"base/frontend/not_exist.k", "base/frontend/not_exist", "appops/projectD/base/base.k", "appops/projectD/base"}

### 3. What did you see instead (Required)

the program returns file not exist error

### 4. What is your KusionStack components version? (Required)
kusion: v0.3.22-alpha.12
kclvm-go: v0.4.2-alpha2

### PR DESCRIPTION
**Pull request by amyXia1994**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [X] Y 
fix #17 

#### 2. What is the scope of this PR (e.g. component or file name):
pkg/tools/list/import_dep_parser.go

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

support deleted files in import deps parser. The `DepOption.ChangedPaths` option now accepts all the file paths that changed. 

A file is "changed" when it's newly added, its content is modified, or it's deleted. The deps parser inspects all the entrance files and builds a dependency tree and the API `ListDownStreamFiles` returns all the files that have a dependency on the changed files by traversing the tree.

- [X] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

**Changes in user behaviors:**
- currently, the API `ListDownStreamFiles` will check each file path and report an error when the file path does not exist. In this PR it only checks the existence of all the entrance files but treats inexistence file paths in ChangedPaths as deleted.
- If there are imports to the deleted files, the `ListDownStreamFiles` API will return all the file paths and package paths that directly or indirectly rely on them.

**Changes in usage:**
- deleted files can be passed in the `ChangedPaths` option now.

**Any incompatible changes in usage: **None

**Precautions for use:**
- do NOT pass deleted file path in the `DepOption.Files` option which represents the entrance files of the KCL program to be analyzed.  Only `DepOption.ChangedPaths` option accepts deleted file paths (and added/modified file paths, of course).

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [X] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

The test case in pkg/tools/list/dep_parser_test.go TestDepParser_affected is used to test API: ListDownStreamFiles. This PR adds some test cases about changed paths containing deleted files

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
support deleted files in ListDownStreamFiles API
```

### CODE REVIEW

File: pkg/tools/list/graph.go [hunk 1]
```diff
@@ -57,6 +56,27 @@ type Identifier interface {
 	Id() string
 }
 
+type IdentifierSet struct {
```
Comment (Peefy) [inline pkg/tools/list/graph.go]: move `IdentifierSet` to another pkg? such as `pkg/data_structure/set.go`? and add some comments and examples on it

File: pkg/tools/list/graph.go [hunk 2]
```diff
@@ -32,15 +31,15 @@ type Grapher interface {
...
-	vertices set.Set
+	vertices *IdentifierSet
 	// edges defines all the edges in the graph
-	edges set.Set
+	edges *IdentifierSet
 	// inboundEdges defines a mapping of the vertices and their inbound edges in the graph.
-	// The key is the vertex id and the value is a set of all the inbound edges to the vertex.
-	inboundEdges map[string]set.Set
+	// The key is the vertex id and the value is a map of all the inbound edges to the vertex.
+	inboundEdges map[string]*IdentifierSet
```
Comment (Peefy) [inline pkg/tools/list/graph.go]: Why use `IdentifierSet` instead of `set.Set`?

File: pkg/tools/list/graph.go [hunk 3]
```diff
@@ -90,32 +110,27 @@ func (g *Graph) Draw() string {
 }
 
 // AddVertex inserts a node to the graph
-func (g *Graph) AddVertex(vertex Vertex) Vertex {
-	if vertex == nil {
-		return nil
-	}
+func (g *Graph) AddVertex(vertex Vertex) {
 	g.vertices.Add(vertex)
```
Comment (Peefy) [inline pkg/tools/list/graph.go]: What happens when `vertex` is `nil`? Could you pls add some comments?

File: pkg/data_structure/set.go [hunk 4]
```diff
@@ -0,0 +1,26 @@
+package data_structure
```
Comment (chai2010) [inline pkg/data_structure/set.go]: data_structure is not a good name. for example in std lib, use [container/list](https://pkg.go.dev/container/list).

for this package, the `IdentifierSet` only include small code, copy the code is better.

File: pkg/tools/list/graph.go [hunk 5]
```diff
@@ -52,84 +53,64 @@ func NewDirectedAcyclicGraph() *DirectedAcyclicGraph {
...
-}
-
-func (s *IdentifierSet) Size() int {
-	return len(s.ids)
-}
-
 // Vertex defines the node with in a graph with a unique id for index
 type Vertex interface {
-	Identifier
+	ds.Identifier
```
Comment (chai2010) [inline pkg/tools/list/graph.go]: Vertex and Edge use interface seems complication. keep the data struct simple is better, use struct is the first choice. the Vertex value field may be Object struct or interface.

File: pkg/tools/list/graph.go [hunk 6]
```diff
@@ -141,17 +122,30 @@ func (g *Graph) DeleteVertex(id string) error {
 
 	// delete the vertex from the vertices map
 	g.vertices.Remove(id)
+
+	// delete the edge from the edges map
+	for edge := range g.edges {
+		if edge.Source().Id() == id || edge.Target().Id() == id {
+			delete(g.edges, edge)
```
Comment (chai2010) [inline pkg/tools/list/graph.go]: do not delete map item in for range map, it is danger.

File: pkg/tools/list/graph.go (hunk 1 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: fixed as commented

File: pkg/tools/list/graph.go (hunk 5 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: fixed, ptal

File: pkg/data_structure/set.go (hunk 4 above)
Comment (amyXia1994) [reply pkg/data_structure/set.go]: It seems there are some different points of view between your suggestion and Peefy's.

File: pkg/tools/list/graph.go (hunk 6 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: I used to think so too but after some digging, I found it safe: Although in many languages deleting while iterating is dangerous, it's safe in Go. 
ref: 
- https://go.dev/ref/spec#For_statements
- https://stackoverflow.com/questions/23229975/is-it-safe-to-remove-selected-keys-from-map-within-a-range-loop

File: pkg/tools/list/graph.go (hunk 2 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: The set.Set(https://github.com/deckarep/golang-set) is not very applicable since the v1 version of it uses interface{} as the type of the set item.
IdentifierSet is simpler.

File: pkg/data_structure/set.go (hunk 4 above)
Comment (ldxdl) [reply pkg/data_structure/set.go]: If we will maintain various types of data structures, it is recommended to:
data_structures/collect/...
data_structures/graph/...
data_structures/tree/...

Comment (ldxdl) [reply pkg/data_structure/set.go]: This implementation is too simple..  and there is no documentation whatsoever. Many details are not clear, for example, is it thread safe... I wonder if we need to write such a toy? And there are already plenty of go set implementations available.

File: pkg/tools/list/graph.go (hunk 1 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: remove the exported IdentifierSet data structure and use an unexported simple stringSet instead. ptal

File: pkg/data_structure/set.go (hunk 4 above)
Comment (amyXia1994) [reply pkg/data_structure/set.go]: removed the exported IdentifierSet data structure and use an unexported simple stringSet struct within the package `list` instead. ptal

File: pkg/tools/list/graph.go (hunk 5 above)
Comment (amyXia1994) [reply pkg/tools/list/graph.go]: removed the general graph/vertex/edge interface and instead use a simple `importGraph` struct without introducing any complicated data structure. ptal

**Comment by ldxdl** [comment]
1. Clarify your pub APIs clearly, and do not pub unnecessary parts.
2. For pub APIs, pls add docstring about why(purpose, scenes, target-problem...), what(spec, desc, usage..) and how(algorithm, solution..).
3. For important impl structs or functions, pls add comments about core design, algorithm and any necessary desc to help others understand how your code works. You can assume that you are explaining the implementation and examples to others here.
4. Make your core function flow clear and readable, and do abstract by purpose to make your code easy to read and understand.
5. More tests and add benchmark for you pub APIs. Ensure that performance is better than your intended target.

**Comment by amyXia1994** [comment]
benchmark:

bench test on API: ListDownStreamFiles/ListUpStreamFiles
```
cd ${PROJECT_ROOT}
go test -run=None -bench=BenchmarkImportDepParser_List\.\*

goos: darwin
goarch: amd64
pkg: kusionstack.io/kclvm-go
cpu: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
BenchmarkImportDepParser_ListDownStreamFiles-4              1369            752212 ns/op
BenchmarkImportDepParser_ListUpStreamFiles-4                1257            812721 ns/op
PASS
ok      kusionstack.io/kclvm-go 4.515s
```

bench test on walking the importGraph upstream/downstream :
```
cd ${PROJECT_ROOT}/pkg/tools/list
go test -bench=.
goos: darwin
goarch: amd64
pkg: kusionstack.io/kclvm-go/pkg/tools/list
cpu: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
BenchmarkImportDepParser_walkDownStream-4         327379              4866 ns/op
BenchmarkImportDepParser_walkUpStreamFiles-4     1666066               676.0 ns/op
PASS
ok      kusionstack.io/kclvm-go/pkg/tools/list  5.663s
```

File: bench_test.go [hunk 7]
```diff
@@ -69,3 +69,43 @@ func tLoadFile(tb testing.TB, path string) string {
...
+		"base/frontend/server/server.k",
+		"base/frontend/server",
+		"appops/projectA/base",
+		"appops/projectA/base/base.k",
+	},
+}
+
+func BenchmarkImportDepParser_ListDownStreamFiles(b *testing.B) {
+	for i := 0; i < b.N; i++ {
+		_, _ = ListDownStreamFiles(listUpDownStreamData.root, &ListDepsOption{Files: listUpDownStreamData.files, UpStreams: listUpDownStreamData.changed})
```
Comment (chai2010) [inline bench_test.go]: `if err != nil { b.Fatal(err) }`

File: pkg/tools/list/testdata/complicate/base/frontend/container/probe/probe.k [hunk 8]
```diff
@@ -0,0 +1,7 @@
+schema Probe:
+    handler:                 Exec | Http | Tcp
```
Comment (Peefy) [inline pkg/tools/list/testdata/complicate/base/frontend/container/probe/probe.k:2]: Unify the use of spaces and tabs in the `Probe` schema.

File: pkg/tools/list/list.go [hunk 9]
```diff
@@ -40,25 +84,76 @@ func ListUpStreamFiles(workDir string, opt *DepOption) (deps []string, err error
...
+//
+// 	import base
+//
+// Then its DownStream files will be: base, base/a.k and base/b.k
+// And if the import statement in main.k changes to:
+//
+// 	import base
+// And the DownStream files/packages of the file base/a.k stays the same
+//
 func ListDownStreamFiles(workDir string, opt *DepOption) ([]string, error) {
```
Comment (Peefy) [inline pkg/tools/list/list.go]: `DepOption` or `DepOptions`?

File: pkg/tools/list/import_dep_parser.go [hunk 10]
```diff
@@ -3,195 +3,362 @@
...
 	pathpkg "path"
+	"path/filepath"
 	"sort"
 	"strings"
 )
 
 var _ = fmt.Sprint
 
-// DepOption defines the option to parse dependency info
+// DepOption provides the files to inspect and list dependency on
```
Comment (Peefy) [inline pkg/tools/list/import_dep_parser.go]: dependencies?

File: pkg/tools/list/import_dep_parser.go [hunk 11]
```diff
@@ -3,195 +3,362 @@
...
 type DepOption struct {
-	// Files is a list of relative file paths. The deps parser will parse the import information starting from these files
+	// Files defines the scope to inspect the import dependency on.
+	// Each value in the list should be a file or package path relative to the workdir.
 	Files []string
-	// ChangedPaths is a list of relative file paths whose content are changed.
-	// The deps parser can filter the Files by the ChangedPaths to distinguish the downstream Files of the ChangedPaths
-	ChangedPaths []string
+	// UpStreams defines a list of UpStream file/package paths to ListDownStreamFiles on. Each value in the list should be a file or package path relative to the workdir.
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: the line comment is too long

File: pkg/tools/list/dep_parser_test.go [hunk 12]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
-var testDepParser = []struct {
-	name     string
-	root     string
-	files    []string
-	depFiles []string
-	changed  []string
-	affected []string
+func BenchmarkImportDepParser_walkDownStream(b *testing.B) {
+	testdata := testImportDepParser[0]
+	depParser, err := newImportDepParser(testdata.root, DepOption{Files: testdata.files, UpStreams: testdata.changed})
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: - `if err != nil { b.Fatal(err) }`
- `b.ResetTimer()` before `for loop`

File: pkg/tools/list/dep_parser_test.go [hunk 13]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
+	if err == nil {
+		for i := 0; i < b.N; i++ {
+			_ = depParser.downStreamFiles()
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: `if err != nil { b.Fatal(err) }`

File: pkg/tools/list/dep_parser_test.go [hunk 14]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
+			expect:     "frontend",
+		},
+		{
+			name:       "invalid import: out of program bound",
+			filePath:   "base/a.k",
+			importPath: "...frontend",
+			expect:     "frontend",
+		},
+	}
+	for _, tData := range testData {
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: `for _, tc := range testCases {` https://github.com/golang/go/blob/master/src/image/jpeg/reader_test.go#L37

File: pkg/tools/list/dep_parser_test.go [hunk 15]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
+		t.Run(tData.name, func(t *testing.T) {
+			assert.Equal(t, tData.expect, fixImportPath(tData.filePath, tData.importPath))
+		})
+	}
+}
+
+func TestImportDepParser_fixPath(t *testing.T) {
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: s/`TestImportDepParser_fixPath`/`Test_fixPath`: fixPath is not the `ImportDepParser` method

File: pkg/tools/list/dep_parser_test.go [hunk 16]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
+	}
+	for _, tData := range testData {
+		t.Run(tData.name, func(t *testing.T) {
+			vfs := os.DirFS("./testdata/complicate")
+			assert.Equal(t, tData.expect, fixPath(vfs, tData.oriPath))
+		})
+	}
+}
+
+func TestImportDepParser_listKFiles(t *testing.T) {
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: s/TestImportDepParser_listKFiles/Test_listKFiles

File: pkg/tools/list/dep_parser_test.go [hunk 17]
```diff
@@ -37,53 +37,189 @@ func TestFindPkgInfo_failed(t *testing.T) {
...
+	}
+	for _, tData := range testData {
+		t.Run(tData.name, func(t *testing.T) {
+			vfs := os.DirFS("./testdata/complicate")
+			assert.ElementsMatch(t, tData.expect, listKFiles(vfs, tData.filePath))
+		})
+	}
+}
+func TestImportDepParser_invalidFilePath(t *testing.T) {
+	t.Run("newImportDepParser invalid file path", func(t *testing.T) {
```
Comment (chai2010) [inline pkg/tools/list/dep_parser_test.go]: `t.Run` is for multi-goroutine test, keep simple for normal test

File: pkg/tools/list/import_dep_parser.go [hunk 18]
```diff
@@ -3,195 +3,362 @@
...
+			return nil, fmt.Errorf("invalid file path: %s", err)
+		}
+	}
+	p := &importDepParser{
+		vfs:         vfs,
+		importGraph: newImportGraph(),
+		opt:         opt,
+	}
+	for _, file := range opt.Files {
+		p.inspect(file)
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go:59]: catch p.inspect panic

File: pkg/tools/list/import_dep_parser.go [hunk 19]
```diff
@@ -3,195 +3,362 @@
...
+		fileIndexInverted:   make(map[string]string),
+		fileIndex:           make(map[string]*stringSet),
+		processed:           emptyStringSet(),
+	}
 }
 
-func (v *FileVertex) Id() string {
-	return v.path
+// stringSet is a simple string set implementation by map
+type stringSet struct {
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: `type stringSet map[string]bool`

or

```
type stringSet []string // do not need call make(...) for init value
````

File: pkg/tools/list/import_dep_parser.go [hunk 20]
```diff
@@ -3,195 +3,362 @@
...
+	values map[string]bool
 }
 
-func (e *DepsEdge) Id() string {
-	return fmt.Sprintf("%s->%s", e.source.Id(), e.target.Id())
+// emptyStringSet creates a string set with an empty value list
+func emptyStringSet() *stringSet {
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: remove `emptyStringSet`, use `make(stringSet)`

File: pkg/tools/list/import_dep_parser.go [hunk 21]
```diff
@@ -3,195 +3,362 @@
...
-// NewImportDepParser initialize an import dependency parser from the given pkg root and the deps option
-func NewImportDepParser(root string, opt DepOption) (*ImportDepParser, error) {
-	root = pathpkg.Clean(root)
-	vfs := os.DirFS(root)
-	for _, file := range opt.Files {
-		if _, err := fs.Stat(vfs, file); err != nil {
-			return nil, fmt.Errorf("invalid file path: %s", err)
-		}
+// toStringSlice generates a string slice containing all the string values in the stringSet s
+func (s *stringSet) toStringSlice() []string {
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: `toSlice()`

File: pkg/tools/list/import_dep_parser.go [hunk 22]
```diff
@@ -3,195 +3,362 @@
...
+	var result []string
+	for value := range s.values {
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: the slice order is random, add comment or return stable order list

**Review by chai2010 — COMMENTED** [review]
add example test

**Comment by amyXia1994** [comment]
The PR brings some performance and memory improvement on API ```ListDownStreamFiles```、```ListUpStreamFiles```  and import graph walking.

I've collected benchmark results five times before and after, then run [benchstat](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) between old and new:

on API: ListDownStreamFiles/ListUpStreamFiles
```
name                                   old time/op    new time/op    delta
ImportDepParser_ListDownStreamFiles-4    1.78ms ±17%    0.80ms ±13%  -54.91%  (p=0.008 n=5+5)
ImportDepParser_ListUpStreamFiles-4      1.52ms ±14%    0.98ms ±25%  -36.03%  (p=0.008 n=5+5)

name                                   old alloc/op   new alloc/op   delta
ImportDepParser_ListDownStreamFiles-4    25.9kB ± 0%    23.3kB ± 0%  -10.04%  (p=0.008 n=5+5)
ImportDepParser_ListUpStreamFiles-4      25.8kB ± 0%    22.8kB ± 0%  -11.41%  (p=0.008 n=5+5)

name                                   old allocs/op  new allocs/op  delta
ImportDepParser_ListDownStreamFiles-4       285 ± 0%       223 ± 0%  -21.75%  (p=0.008 n=5+5)
ImportDepParser_ListUpStreamFiles-4         283 ± 0%       220 ± 0%  -22.26%  (p=0.008 n=5+5)
```

on walking the importGraph upstream/downstream
```
name                                 old time/op    new time/op    delta
ImportDepParser_walkDownStream-4       11.0µs ±15%     5.1µs ±58%  -53.65%  (p=0.008 n=5+5)
ImportDepParser_walkUpStreamFiles-4    7.65µs ± 4%    1.12µs ±20%  -85.42%  (p=0.008 n=5+5)

name                                 old alloc/op   new alloc/op   delta
ImportDepParser_walkDownStream-4         696B ± 0%      600B ± 0%  -13.79%  (p=0.008 n=5+5)
ImportDepParser_walkUpStreamFiles-4      608B ± 0%      264B ± 0%  -56.58%  (p=0.008 n=5+5)

name                                 old allocs/op  new allocs/op  delta
ImportDepParser_walkDownStream-4         11.0 ± 0%       8.0 ± 0%  -27.27%  (p=0.008 n=5+5)
ImportDepParser_walkUpStreamFiles-4      9.00 ± 0%      5.00 ± 0%  -44.44%  (p=0.008 n=5+5)
```

**Review by Peefy — DISMISSED** [review]
LGTM

File: pkg/tools/list/import_dep_parser.go [hunk 23]
```diff
@@ -3,195 +3,377 @@
...
+		}
+	}
+	p = &importDepParser{
+		vfs:         vfs,
+		importGraph: newImportGraph(),
+		opt:         opt,
+	}
+	defer func() {
+		if r := recover(); r != nil {
+			err = errors.New(fmt.Sprintf("%s", r))
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: `fmt.Sprintf("%v", r)`

File: pkg/tools/list/import_dep_parser.go [hunk 24]
```diff
@@ -3,195 +3,377 @@
...
+	for _, f := range kFiles {
+		// 3.1 record index and reverted index of file/packages
+		p.importGraph.fileIndexInverted[f] = pkgPath
+		addValueOnIndex(p.importGraph.fileIndex, pkgPath, f)
+
+		// 3.2 read file content and extract import paths from it
 		src, err := fs.ReadFile(p.vfs, f)
 		if err != nil {
-			panic(err)
+			panic(err.Error())
```
Comment (chai2010) [inline pkg/tools/list/import_dep_parser.go]: `panic(err)`

**Review by chai2010 — APPROVED** [review]
LGTM

**Review by Peefy — APPROVED** [review]
LGTM
